server:
  port: 8084

spring:
  application:
    name: ebuy-mail-service
  kafka:
    bootstrap-servers: rocket-01.srvs.cloudkafka.com:9094,rocket-02.srvs.cloudkafka.com:9094,rocket-03.srvs.cloudkafka.com:9094
    consumer:
      group-id: xha6ilg6-consumers
      auto-offset-reset: latest
    topic:
      userRegistered: xha6ilg6-useregister
      userPassword: xha6ilg6-userpassword
    properties:
      security:
        protocol: SASL_SSL
      sasl:
        mechanism: SCRAM-SHA-256
        jaas:
          config: org.apache.kafka.common.security.scram.ScramLoginModule required username='xha6ilg6' password='1MA15i4ysm1Rl-Nnwd1SlS2kgDUtFFOt';
        linger:
          ms: 100
  mail:
    host: smtp.gmail.com
    port: 587
    username: ebuytestuser@gmail.com
    password: Asdf1234.
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp



eureka:
  client:
    service-url:
      defaultZone: https://ebuy-registry-service.herokuapp.com/eureka
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
  instance:
    preferIpAddress: true
